/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.task1;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.io.Writer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Adam
 */
public class DataAnalyse extends javax.swing.JFrame {

    /**
     * Creates new form DataAnalyse
     */
    public DataAnalyse() {
        initComponents();
//        calculation = new Calculation();
//        try {
//            this.output = new PrintWriter("wyniki.txt", "UTF-8");
//        } catch (FileNotFoundException ex) {
//            Logger.getLogger(DataAnalyse.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (UnsupportedEncodingException ex) {
//            Logger.getLogger(DataAnalyse.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        separatorArea = new javax.swing.JTextField();
        JButtonHistogram = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNumberOfColumn = new javax.swing.JTextField();
        jButtonGroupAndDrawHistogram = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Obliczenia");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        separatorArea.setText(",");
        separatorArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                separatorAreaActionPerformed(evt);
            }
        });

        JButtonHistogram.setText("Histogram");
        JButtonHistogram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonHistogramActionPerformed(evt);
            }
        });

        jLabel1.setText("Wpisz numer kolumny");

        jButtonGroupAndDrawHistogram.setText("Grupuj i rysuj histogram");
        jButtonGroupAndDrawHistogram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGroupAndDrawHistogramActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("Open file");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Save File");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldNumberOfColumn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(separatorArea, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JButtonHistogram)
                    .addComponent(jLabel1)
                    .addComponent(jButtonGroupAndDrawHistogram))
                .addGap(0, 253, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(separatorArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNumberOfColumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonHistogram)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonGroupAndDrawHistogram)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
//        separator = sepArea.getText();
        Object z = evt.getSource();
//        if (jMenuItem1 == z) {
        JFileChooser fc = new JFileChooser();
        if (fc.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            sourceFile = fc.getSelectedFile();
        }
//        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked

    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
//        output.println("Średnia artmetyczna");
//        output.println(fillFile.arithmeticAverageForOneColumn(sourceFile, separator));
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        separator = separatorArea.getText();
        Calculation calculation = new Calculation(sourceFile, separator );
        
        try {
            this.output = new PrintWriter("wyniki.txt", "UTF-8");
        } catch (FileNotFoundException | UnsupportedEncodingException ex) {
            Logger.getLogger(DataAnalyse.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        output.println("Plik wejściowy: " + sourceFile.getName());
        output.println("Separator: " + separator);
        output.println(calculation.getClassTypeCollection());
        output.println(calculation.result());
        output.println("koniec");
        output.close();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void separatorAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_separatorAreaActionPerformed
        
    }//GEN-LAST:event_separatorAreaActionPerformed

    private void JButtonHistogramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonHistogramActionPerformed
        Calculation licz = new Calculation(sourceFile , separatorArea.getText());
        Chart chart = new Chart (licz) ;
        int number;
        number = Integer.parseInt (jTextFieldNumberOfColumn.getText() );
        chart.makeChart(number);
    }//GEN-LAST:event_JButtonHistogramActionPerformed

    private void jButtonGroupAndDrawHistogramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGroupAndDrawHistogramActionPerformed
        Calculation licz = new Calculation(sourceFile , separatorArea.getText());
        Chart chart = new Chart (licz) ;
        int number;
        number = Integer.parseInt (jTextFieldNumberOfColumn.getText() );
        chart.makeGroupedDataChart(number);
    }//GEN-LAST:event_jButtonGroupAndDrawHistogramActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataAnalyse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataAnalyse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataAnalyse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataAnalyse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataAnalyse().setVisible(true);
            }
        });
    }
    private String separator;
    private File sourceFile;
    private PrintWriter output;
    //private Calculation calculation;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonHistogram;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonGroupAndDrawHistogram;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField jTextFieldNumberOfColumn;
    private javax.swing.JTextField separatorArea;
    // End of variables declaration//GEN-END:variables
}
